# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04c8013648559e76eb76724b74d164d812d352a754c287afc70e7b5c013c8d73522a6bb43e227a11fa92860d94a3beff60e805a72f0acb04ca72a646349ec4b6

test:
  secret_key_base: 3b17ffb4b86a1d77947129633b34671000cf3b172b253ed05f606eb045b43bfedc856563f825197d3bc76b8dfc1e4e26436e98505ca6e155c95ad87fac081ed9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
